// Mock user data for collaborative filtering
export const mockUsers = [
  {
    id: "user1",
    name: "Alex",
    gender: "male",
    age: 28,
    weight: "75kg",
    preferredEquipment: ["dumbbells", "resistance bands", "bodyweight"],
    preferredMuscleGroups: ["Upper Body Push", "Core", "Arms"],
    completedWorkouts: [
      {
        id: "workout1",
        date: "2023-04-15",
        workoutPlanId: "plan1",
        duration: 45,
        muscleGroups: ["Upper Body Push", "Arms"],
        difficulty: "intermediate",
      },
      {
        id: "workout2",
        date: "2023-04-18",
        workoutPlanId: "plan4",
        duration: 50,
        muscleGroups: ["Upper Body Push", "Lower Body Push", "Core"],
        difficulty: "intermediate",
      },
    ],
    ratings: [
      { workoutPlanId: "plan1", rating: 4, timestamp: 1681574400000 },
      { workoutPlanId: "plan4", rating: 5, timestamp: 1681747200000 },
    ],
  },
  {
    id: "user2",
    name: "Jamie",
    gender: "female",
    age: 32,
    weight: "62kg",
    preferredEquipment: ["resistance bands", "bodyweight"],
    preferredMuscleGroups: ["Lower Body Push", "Core", "Shoulders"],
    completedWorkouts: [
      {
        id: "workout3",
        date: "2023-04-14",
        workoutPlanId: "plan3",
        duration: 60,
        muscleGroups: ["Lower Body Push", "Core"],
        difficulty: "intermediate",
      },
    ],
    ratings: [{ workoutPlanId: "plan3", rating: 5, timestamp: 1681488000000 }],
  },
  {
    id: "user3",
    name: "Sam",
    gender: "male",
    age: 25,
    weight: "80kg",
    preferredEquipment: ["barbells", "dumbbells", "machine"],
    preferredMuscleGroups: ["Upper Body Push", "Upper Body Pull", "Lower Body Push"],
    completedWorkouts: [
      {
        id: "workout4",
        date: "2023-04-16",
        workoutPlanId: "plan5",
        duration: 75,
        muscleGroups: ["Upper Body Push", "Upper Body Pull"],
        difficulty: "advanced",
      },
    ],
    ratings: [{ workoutPlanId: "plan5", rating: 5, timestamp: 1681660800000 }],
  },
  {
    id: "user4",
    name: "Jordan",
    gender: "non-binary",
    age: 30,
    weight: "70kg",
    preferredEquipment: ["kettlebells", "barbells", "machine"],
    preferredMuscleGroups: ["Upper Body Pull", "Shoulders", "Lower Body Pull"],
    completedWorkouts: [
      {
        id: "workout5",
        date: "2023-04-17",
        workoutPlanId: "plan5",
        duration: 75,
        muscleGroups: ["Upper Body Push", "Upper Body Pull"],
        difficulty: "advanced",
      },
      {
        id: "workout6",
        date: "2023-04-19",
        workoutPlanId: "plan7",
        duration: 60,
        muscleGroups: ["Upper Body Pull", "Shoulders"],
        difficulty: "advanced",
      },
    ],
    ratings: [
      { workoutPlanId: "plan5", rating: 4, timestamp: 1681747200000 },
      { workoutPlanId: "plan7", rating: 5, timestamp: 1681920000000 },
    ],
  },
]

// Mock workout plans
export const mockWorkoutPlans = [
  {
    id: "plan1",
    name: "Upper Body Strength",
    muscleGroups: ["Upper Body Push", "Arms"],
    equipment: ["dumbbells", "resistance bands"],
    difficulty: "intermediate",
    duration: 45,
    popularity: 85,
  },
  {
    id: "plan2",
    name: "Core Stability",
    muscleGroups: ["Core"],
    equipment: ["bodyweight", "resistance bands"],
    difficulty: "beginner",
    duration: 30,
    popularity: 90,
  },
  {
    id: "plan3",
    name: "Lower Body Focus",
    muscleGroups: ["Lower Body Push", "Core"],
    equipment: ["resistance bands", "bodyweight"],
    difficulty: "intermediate",
    duration: 60,
    popularity: 75,
  },
  {
    id: "plan4",
    name: "Full Body Toning",
    muscleGroups: ["Upper Body Push", "Lower Body Push", "Core"],
    equipment: ["dumbbells", "resistance bands"],
    difficulty: "intermediate",
    duration: 50,
    popularity: 80,
  },
  {
    id: "plan5",
    name: "Advanced Upper Body",
    muscleGroups: ["Upper Body Push", "Upper Body Pull"],
    equipment: ["barbells", "dumbbells", "machine"],
    difficulty: "advanced",
    duration: 75,
    popularity: 70,
  },
  {
    id: "plan6",
    name: "Arms & Shoulders",
    muscleGroups: ["Arms", "Shoulders"],
    equipment: ["dumbbells", "resistance bands"],
    difficulty: "intermediate",
    duration: 40,
    popularity: 65,
  },
  {
    id: "plan7",
    name: "Back & Shoulders",
    muscleGroups: ["Upper Body Pull", "Shoulders"],
    equipment: ["barbells", "machine", "kettlebells"],
    difficulty: "advanced",
    duration: 60,
    popularity: 60,
  },
  {
    id: "plan8",
    name: "HIIT Cardio",
    muscleGroups: ["Upper Body Push", "Lower Body Push", "Core"],
    equipment: ["bodyweight", "kettlebells"],
    difficulty: "advanced",
    duration: 30,
    popularity: 85,
  },
  {
    id: "plan9",
    name: "Beginner Full Body",
    muscleGroups: ["Upper Body Push", "Upper Body Pull", "Lower Body Push", "Lower Body Pull"],
    equipment: ["dumbbells", "bodyweight"],
    difficulty: "beginner",
    duration: 45,
    popularity: 95,
  },
  {
    id: "plan10",
    name: "Functional Strength",
    muscleGroups: ["Core", "Shoulders", "Lower Body Push"],
    equipment: ["kettlebells", "resistance bands"],
    difficulty: "intermediate",
    duration: 50,
    popularity: 75,
  },
]
